using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using UIFramework.Data.Model;

namespace UIFramework.Data.Loading
{
    /// <summary>
    /// <c>ui_schema</c>: writes JSON Schemas generated by reflection over the definition models, with descriptions from
    /// the assembly's XML documentation when it ships next to the DLL. <c>menu.schema.json</c> validates a standalone
    /// definition file (a <c>From</c> target), <c>menus.schema.json</c> the whole <c>Menus</c> asset, <c>huds.schema.json</c> /
    /// <c>owners.schema.json</c> the <c>Huds</c> / <c>Owners</c> assets,
    /// <c>sprites.schema.json</c> the <c>Sprites</c> asset and (v1.7) <c>composites.schema.json</c> /
    /// <c>contributions.schema.json</c> the <c>Composites</c> / <c>Contributions</c> assets. Associate them with your files in VS Code through
    /// <c>json.schemas</c> or a <c>"$schema"</c> member.
    /// </summary>
    internal static class SchemaWriter
    {
        private static readonly Type[] Models = { typeof(MenuDefinition), typeof(ElementDefinition), typeof(StyleDefinition), typeof(ActionDefinition), typeof(SpriteDefinition),
            typeof(HudDefinition), typeof(OwnerDefinition), typeof(HotkeyDefinition), typeof(KeyBindingDefinition), typeof(SourceDefinition), typeof(ColumnDefinition),
            typeof(TooltipDefinition), typeof(TooltipBlockDefinition), typeof(FormFieldDefinition), typeof(TemplateDefinition), typeof(ParamDefinition),
            typeof(DataCompositeDefinition), typeof(ContributionDefinition), typeof(DecorationOp) };

        /// <summary>Write the schemas into <paramref name="directory"/>; returns the files written.</summary>
        internal static string[] Write(string directory)
        {
            Directory.CreateDirectory(directory);
            Dictionary<string, string> docs = LoadDocs();
            JObject definitions = BuildDefinitions(docs);

            var written = new List<string>
            {
                WriteFile(directory, "menu.schema.json", MenuSchema(definitions)),
                WriteFile(directory, "menus.schema.json", Root($"UI Framework {DataAssets.Menus} asset", definitions, new JObject
                {
                    ["type"] = "object",
                    ["additionalProperties"] = new JObject { ["$ref"] = "#/definitions/MenuDefinition" }
                })),
                WriteFile(directory, "huds.schema.json", Root($"UI Framework {DataAssets.Huds} asset", definitions, new JObject
                {
                    ["type"] = "object",
                    ["additionalProperties"] = new JObject { ["$ref"] = "#/definitions/HudDefinition" }
                })),
                WriteFile(directory, "owners.schema.json", Root($"UI Framework {DataAssets.Owners} asset", definitions, new JObject
                {
                    ["type"] = "object",
                    ["additionalProperties"] = new JObject { ["$ref"] = "#/definitions/OwnerDefinition" }
                })),
                WriteFile(directory, "sprites.schema.json", Root($"UI Framework {DataAssets.Sprites} asset", definitions, new JObject
                {
                    ["type"] = "object",
                    ["additionalProperties"] = new JObject { ["$ref"] = "#/definitions/SpriteDefinition" }
                })),
                WriteFile(directory, "composites.schema.json", Root($"UI Framework {DataAssets.Composites} asset", definitions, new JObject
                {
                    ["type"] = "object",
                    ["additionalProperties"] = new JObject { ["$ref"] = "#/definitions/DataCompositeDefinition" }
                })),
                WriteFile(directory, "contributions.schema.json", Root($"UI Framework {DataAssets.Contributions} asset", definitions, new JObject
                {
                    ["type"] = "object",
                    ["additionalProperties"] = new JObject { ["$ref"] = "#/definitions/ContributionDefinition" }
                }))
            };
            return written.ToArray();
        }

        /// <summary>The schema <c>menu.schema.json</c> holds (also read by the designer's metadata generator).</summary>
        internal static JObject MenuSchema() => MenuSchema(BuildDefinitions(LoadDocs()));

        private static JObject MenuSchema(JObject definitions)
        {
            return Root("UI Framework data menu (a Menus entry or a standalone From file)", definitions, new JObject { ["$ref"] = "#/definitions/MenuDefinition" });
        }

        private static JObject Root(string title, JObject definitions, JObject body)
        {
            var root = new JObject
            {
                ["$schema"] = "http://json-schema.org/draft-07/schema#",
                ["title"] = title
            };
            foreach (JProperty property in body.Properties())
            {
                root[property.Name] = property.Value.DeepClone();
            }

            root["definitions"] = definitions.DeepClone();
            return root;
        }

        private static string WriteFile(string directory, string name, JObject schema)
        {
            string path = Path.Combine(directory, name);
            File.WriteAllText(path, schema.ToString(Formatting.Indented));
            return path;
        }

        private static JObject BuildDefinitions(Dictionary<string, string> docs)
        {
            var definitions = new JObject
            {
                ["Value"] = new JObject
                {
                    ["description"] = "A value: text, a number or true / false (numbers and bools may also be written as strings).",
                    ["type"] = new JArray("string", "number", "boolean")
                },
                ["StringList"] = new JObject
                {
                    ["description"] = "A list of strings, or one comma-separated string.",
                    ["oneOf"] = new JArray(
                        new JObject { ["type"] = "string" },
                        new JObject { ["type"] = "array", ["items"] = new JObject { ["type"] = new JArray("string", "number", "boolean") } })
                },
                ["ActionList"] = new JObject
                {
                    ["description"] = "Actions: a trigger action string, an action object, or an array of either.",
                    ["oneOf"] = new JArray(
                        new JObject { ["type"] = "string" },
                        new JObject { ["$ref"] = "#/definitions/ActionDefinition" },
                        new JObject
                        {
                            ["type"] = "array",
                            ["items"] = new JObject
                            {
                                ["oneOf"] = new JArray(new JObject { ["type"] = "string" }, new JObject { ["$ref"] = "#/definitions/ActionDefinition" })
                            }
                        })
                },
                ["Source"] = new JObject
                {
                    ["description"] = "Where a collection's rows come from: a string (\"menu.items\", \"themes\", \"range:1..10\", \"query:ALL_ITEMS (O)\", \"asset:Data/X\", a Sources entry name; on an Image, the source rectangle \"x,y,w,h\"), an array of inline rows, or a source object.",
                    ["oneOf"] = new JArray(
                        new JObject { ["type"] = "string" },
                        new JObject { ["type"] = "array" },
                        new JObject { ["$ref"] = "#/definitions/SourceDefinition" })
                },
                ["Columns"] = new JObject
                {
                    ["description"] = "Grid: column tracks (\"auto, *, 120\"). DataGrid: the column objects.",
                    ["oneOf"] = new JArray(
                        new JObject { ["type"] = "string" },
                        new JObject { ["type"] = "array", ["items"] = new JObject { ["oneOf"] = new JArray(new JObject { ["type"] = "string" }, new JObject { ["$ref"] = "#/definitions/ColumnDefinition" }) } })
                },
                ["Tooltip"] = new JObject
                {
                    ["description"] = "A rich tooltip: { MaxWidth, Blocks }, the block array alone, or one line of text.",
                    ["oneOf"] = new JArray(
                        new JObject { ["type"] = "string" },
                        new JObject { ["type"] = "array", ["items"] = new JObject { ["$ref"] = "#/definitions/TooltipBlockDefinition" } },
                        new JObject { ["$ref"] = "#/definitions/TooltipDefinition" })
                },
                ["ElementList"] = new JObject
                {
                    ["description"] = "One element or an array of elements.",
                    ["oneOf"] = new JArray(
                        new JObject { ["$ref"] = "#/definitions/ElementDefinition" },
                        new JObject { ["type"] = "array", ["items"] = new JObject { ["$ref"] = "#/definitions/ElementDefinition" } })
                },
                ["StateValue"] = new JObject
                {
                    ["description"] = "A default value (text, number, true / false, a one-time \"$:{...}\"), or a JSON array / object kept as its JSON text for State sources.",
                    ["type"] = new JArray("string", "number", "boolean", "array", "object")
                }
            };

            foreach (Type model in Models)
            {
                definitions[model.Name] = Describe(model, docs);
            }

            return definitions;
        }

        private static JObject Describe(Type model, Dictionary<string, string> docs)
        {
            var properties = new JObject();
            foreach (PropertyInfo property in DataValidator.ModelProperties(model))
            {
                JObject schema = PropertySchema(model, property);
                if (docs.TryGetValue($"P:{model.FullName}.{property.Name}", out string? doc))
                {
                    schema["description"] = doc;
                }

                properties[property.Name] = schema;
            }

            if (model == typeof(MenuDefinition))
            {
                // lets a standalone file point at the schema itself
                properties["$schema"] = new JObject { ["type"] = "string" };
            }

            var result = new JObject
            {
                ["type"] = "object",
                ["properties"] = properties,
                ["additionalProperties"] = false
            };
            if (model == typeof(ElementDefinition))
            {
                // a custom tag (dotted Type) or a template instance (a Type that is no built-in type, or a Template) takes any
                // extra field as an argument; other elements only their members
                result.Remove("additionalProperties");
                result["if"] = new JObject
                {
                    ["anyOf"] = new JArray(
                        new JObject { ["required"] = new JArray("Template") },
                        new JObject
                        {
                            ["properties"] = new JObject { ["Type"] = new JObject { ["type"] = "string", ["not"] = new JObject { ["enum"] = new JArray(ElementTypes.All.Cast<object>().ToArray()) } } },
                            ["required"] = new JArray("Type")
                        })
                };
                result["then"] = new JObject();
                result["else"] = new JObject { ["propertyNames"] = new JObject { ["enum"] = new JArray(properties.Properties().Select(p => (object)p.Name).ToArray()) } };
            }
            if (docs.TryGetValue($"T:{model.FullName}", out string? typeDoc))
            {
                result["description"] = typeDoc;
            }

            return result;
        }

        /// <summary>The definitions of the members read through a list converter.</summary>
        private static readonly Dictionary<Type, string> ConverterDefinitions = new()
        {
            [typeof(ActionListConverter)] = "ActionList",
            [typeof(StringListConverter)] = "StringList",
            [typeof(ColumnListConverter)] = "Columns",
            [typeof(ElementListConverter)] = "ElementList"
        };

        /// <summary>The schemas of members whose values are a fixed set (or free-form), by (model, member name).</summary>
        private static readonly Dictionary<(Type Model, string Member), Func<JObject>> MemberSchemas = new()
        {
            // a built-in type, a custom tag (the dotted global name of a C# or data composite) or a template name (v1.7)
            [(typeof(ElementDefinition), nameof(ElementDefinition.Type))] = () => new JObject
            {
                ["anyOf"] = new JArray(
                    new JObject { ["enum"] = new JArray(ElementTypes.All.Cast<object>().ToArray()) },
                    new JObject { ["type"] = "string" })
            },
            [(typeof(ElementDefinition), nameof(ElementDefinition.Args))] = () => new JObject { ["type"] = "object", ["additionalProperties"] = new JObject() },
            [(typeof(DecorationOp), nameof(DecorationOp.Op))] = () => new JObject { ["enum"] = new JArray(DecorationOps.All.Cast<object>().ToArray()) },
            [(typeof(ParamDefinition), nameof(ParamDefinition.Type))] = () => new JObject { ["enum"] = new JArray("string", "number", "bool", "any") },
            [(typeof(ParamDefinition), nameof(ParamDefinition.Default))] = () => new JObject(),
            [(typeof(SourceDefinition), nameof(SourceDefinition.Type))] = () => new JObject { ["enum"] = new JArray(SourceKinds.All.Cast<object>().ToArray()) },
            [(typeof(TooltipBlockDefinition), nameof(TooltipBlockDefinition.Type))] = () => new JObject { ["enum"] = new JArray(TooltipBlockKinds.All.Cast<object>().ToArray()) },
            [(typeof(FormFieldDefinition), nameof(FormFieldDefinition.Kind))] = () => new JObject { ["enum"] = new JArray("Checkbox", "Number", "Integer", "Text", "Dropdown") }
        };

        /// <summary>The schemas of members by their CLR type.</summary>
        private static readonly Dictionary<Type, Func<JObject>> TypeSchemas = new()
        {
            [typeof(SourceDefinition)] = () => new JObject { ["$ref"] = "#/definitions/Source" },
            [typeof(TooltipDefinition)] = () => new JObject { ["$ref"] = "#/definitions/Tooltip" },
            [typeof(List<JToken>)] = () => new JObject { ["type"] = "array" },
            [typeof(string)] = () => new JObject { ["$ref"] = "#/definitions/Value" }
        };

        private static JObject PropertySchema(Type model, PropertyInfo property)
        {
            JsonConverterAttribute? converter = property.GetCustomAttribute<JsonConverterAttribute>();
            if (converter != null && ConverterDefinitions.TryGetValue(converter.ConverterType, out string? definition))
            {
                return new JObject { ["$ref"] = "#/definitions/" + definition };
            }

            if (MemberSchemas.TryGetValue((model, property.Name), out Func<JObject>? memberSchema))
            {
                return memberSchema();
            }

            Type type = property.PropertyType;
            if (TypeSchemas.TryGetValue(type, out Func<JObject>? typeSchema))
            {
                return typeSchema();
            }

            if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Dictionary<,>))
            {
                return new JObject { ["type"] = "object", ["additionalProperties"] = DictionaryItemSchema(property, type.GetGenericArguments()[1]) };
            }

            if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(List<>))
            {
                Type item = type.GetGenericArguments()[0];
                return new JObject { ["type"] = "array", ["items"] = new JObject { ["$ref"] = "#/definitions/" + item.Name } };
            }

            if (Models.Contains(type))
            {
                return new JObject { ["$ref"] = "#/definitions/" + type.Name };
            }

            return new JObject();
        }

        /// <summary>The schema of a dictionary member's values (of type <paramref name="value"/>).</summary>
        private static JObject DictionaryItemSchema(PropertyInfo property, Type value)
        {
            Type? itemConverter = property.GetCustomAttribute<JsonPropertyAttribute>()?.ItemConverterType;
            if (itemConverter == typeof(JsonTextConverter))
            {
                return new JObject { ["$ref"] = "#/definitions/StateValue" };
            }

            if (value == typeof(SourceDefinition))
            {
                return new JObject { ["$ref"] = "#/definitions/Source" };
            }

            if (value == typeof(string))
            {
                return new JObject { ["$ref"] = "#/definitions/Value" };
            }

            if (itemConverter == typeof(ActionListConverter))
            {
                return new JObject { ["$ref"] = "#/definitions/ActionList" };
            }

            return Models.Contains(value) ? new JObject { ["$ref"] = "#/definitions/" + value.Name } : new JObject();
        }

        /// <summary>Member summaries from <c>UIFramework.xml</c> next to the DLL, keyed by XML doc id (empty when the file is missing).</summary>
        private static Dictionary<string, string> LoadDocs()
        {
            var docs = new Dictionary<string, string>(StringComparer.Ordinal);
            string? directory = Path.GetDirectoryName(typeof(SchemaWriter).Assembly.Location);
            string path = Path.Combine(directory ?? string.Empty, "UIFramework.xml");
            if (!File.Exists(path))
            {
                return docs;
            }

            try
            {
                foreach (XElement member in XDocument.Load(path).Descendants("member"))
                {
                    string? name = member.Attribute("name")?.Value;
                    XElement? summary = member.Element("summary");
                    if (name != null && summary != null && name.Contains(".Data.Model."))
                    {
                        docs[name] = Flatten(summary);
                    }
                }
            }
            catch (Exception ex)
            {
                Core.UIServices.Log($"Could not read {path} for schema descriptions: {ex.Message}");
            }

            return docs;
        }

        /// <summary>Summary text with <c>&lt;c&gt;</c> / <c>&lt;see&gt;</c> reduced to plain text and whitespace collapsed.</summary>
        private static string Flatten(XElement summary)
        {
            IEnumerable<string> parts = summary.Nodes().Select(node => node switch
            {
                XText text => text.Value,
                XElement { Name.LocalName: "see" } see => (see.Attribute("cref")?.Value ?? see.Attribute("langword")?.Value ?? string.Empty).Split('.', ':').Last(),
                XElement element => element.Value,
                _ => string.Empty
            });
            return Regex.Replace(string.Concat(parts), @"\s+", " ").Trim();
        }
    }
}
