<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>GiantCropFertilizerContinued</AssemblyName>
    <RootNamespace>GiantCropFertilizer</RootNamespace>
    <Version>1.0.0</Version>
    <EnableHarmony>true</EnableHarmony>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GamePath>$(STARDEW_GAME_DIR)</GamePath>
    <DefaultItemExcludes>$(DefaultItemExcludes);obj/**;bin/**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="StardewValley" />
    <Using Include="StardewModdingAPI" />
  </ItemGroup>

</Project>
